//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiffinSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderDetail
    {
        public int OrderId { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int UserId { get; set; }
        public int TiffinTypeId { get; set; }
        public int Vendor { get; set; }
        public int ExtraId { get; set; }
        public int Total { get; set; }
    
        public virtual Extra Extra { get; set; }
        public virtual TiffinDetail TiffinDetail { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
