//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiffinSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class UserDetail
    {
        public UserDetail()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.TiffinDetails = new HashSet<TiffinDetail>();
        }
    
        public int UserId { get; set; }

        [Required(ErrorMessage = "First Name cannot be empty")]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Last Name cannot be empty")]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Please select a gender")]
        public int GenderId { get; set; }

        [Required(ErrorMessage = "Phone cannot be empty")]
        public string PhoneNo { get; set; }

        [Required(ErrorMessage = "Email cannot be empty")]
        [DataType(DataType.EmailAddress, ErrorMessage = "Invalid Email Address")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Password cannot be empty")]
        [DataType(DataType.Password, ErrorMessage = "Invalid Password")]
        [MaxLength(30, ErrorMessage = "Password should contain only 30 characters")]
        public string Password { get; set; }

        public int UserTypeId { get; set; }

        public System.DateTime Date { get; set; }
    
        public virtual Gender Gender { get; set; }

        public virtual ICollection<OrderDetail> OrderDetails { get; set; }

        public virtual ICollection<TiffinDetail> TiffinDetails { get; set; }

        public virtual UserType UserType { get; set; }
    }
}
