//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiffinMgmtSystem.Models
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Extra
    {
        public Extra()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }

        [Required]
        [Display(Name = "Extras")]
        public int ExtraId { get; set; }

        [Required]
        public string ExtraName { get; set; }
        public int Cost { get; set; }
    
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
    }
}
