//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiffinMgmtSystem.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Gender
    {
        public Gender()
        {
            this.UserDetails = new HashSet<UserDetail>();
        }

        [Required]
        public int GenderId { get; set; }

        [Required]
        public string Name { get; set; }
    
        public virtual ICollection<UserDetail> UserDetails { get; set; }
    }
}
