//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiffinMgmtSystem.Models
{
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TiffinDetail
    {
        public TiffinDetail()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
        }

        [Required]
        public int Id { get; set; }

        [Required]
        [Display(Name = "Tiffin Type")]
        public string Type { get; set; }
        public int Cost { get; set; }
        public int UserId { get; set; }
   
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual UserDetail UserDetail { get; set; }
    }
}
