//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiffinMgmtSystem.Models
{
    using System.Collections.Generic;
    
    public partial class UserType
    {
        public UserType()
        {
            this.UserDetails = new HashSet<UserDetail>();
        }
    
        public int TypeId { get; set; }
        public string Type { get; set; }
    
        public virtual ICollection<UserDetail> UserDetails { get; set; }
    }
}
